# Asistente de Viaje Inteligente - con 192 combinaciones

companias = ["solo", "pareja", "amigos", "familia"]
tipos_viaje = ["aventura", "relax", "gastronomico", "cultural"]
climas = ["frio (<20ºC)", "templado (20-28ºC)", "calido (>28ºC)"]
preferencias = ["playa", "ciudad", "montaña", "campo"]

recomendaciones = {
    ('solo', 'aventura', 'frio (<20ºC)', 'playa'): 'Una Aventura solo en una playa con clima frio (<20ºC): te sugerimos Sable Island (Canadá), Vik (Islandia).',
    ('solo', 'aventura', 'frio (<20ºC)', 'ciudad'): 'Una Aventura solo en una ciudad de clima frio (<20ºC): te sugerimos Helsinki, Reikiavik, Oslo.',
    ('solo', 'aventura', 'frio (<20ºC)', 'montaña'): 'Una Aventura solo en una montaña con clima frio (<20ºC): te sugerimos Zermatt (Suiza), Banff (Canadá), Tirol (Austria).',
    ('solo', 'aventura', 'frio (<20ºC)', 'campo'): 'Una Aventura solo en el campo con clima frio (<20ºC): te sugerimos Highlands (Escocia), Fiordland (Nueva Zelanda), Región de los Lagos (Alemania).',
    ('solo', 'aventura', 'templado (20-28ºC)', 'playa'): 'Una Aventura solo en una playa con clima templado (20-28ºC): te sugerimos Bahía Magdalena (México), Islas Cíes (España), Corfú (Grecia).',
    ('solo', 'aventura', 'templado (20-28ºC)', 'ciudad'): 'Una Aventura solo en una  ciudad de clima templado (20-28ºC): te sugerimos Santiago de Chile, Lisboa, Buenos Aires.',
    ('solo', 'aventura', 'templado (20-28ºC)', 'montaña'): 'Una Aventura solo en una montaña de clima templado (20-28ºC): te sugerimos Montañas Apalaches (EE.UU.), Tatras (Eslovaquia), Sierra de Gredos (España).',
    ('solo', 'aventura', 'templado (20-28ºC)', 'campo'): 'Una Aventura solo en el campo de clima templado (20-28ºC): te sugerimos Camino de Santiago (España), Napa Valley (EE.UU.).',
    ('solo', 'aventura', 'calido (>28ºC)', 'playa'): 'Una Aventura solo en una playa de clima calido (>28ºC): te sugerimos Praia do Forte (Brasil).',
    ('solo', 'aventura', 'calido (>28ºC)', 'ciudad'): 'Una Aventura solo en una ciudad de clima calido (>28ºC): te sugerimos La Habana, Bangkok.',
    ('solo', 'aventura', 'calido (>28ºC)', 'montaña'): 'Una Aventura solo en una montaña de clima calido (>28ºC): te sugerimos Mocoa (Colombia), Sierra Nevada (Venezuela).',
    ('solo', 'aventura', 'calido (>28ºC)', 'campo'): 'Una Aventura solo en el campo de clima calido (>28ºC): te sugerimos Yucatán (México), Plaines de Luang Prabang (Laos).',
    ('solo', 'relax', 'frio (<20ºC)', 'playa'): 'Relax solo en una playa de clima frio (<20ºC): te sugerimos Vik (Islandia), Isla de Skye (Escocia), Sable Island (Canadá).',
    ('solo', 'relax', 'frio (<20ºC)', 'ciudad'): 'Relax solo en una ciudad de clima frio (<20ºC): te sugerimos Helsinki, Oslo.',
    ('solo', 'relax', 'frio (<20ºC)', 'montaña'): 'Relax solo en una montaña de clima frio (<20ºC): te sugerimos Banff (Canadá), Tirol (Austria).',
    ('solo', 'relax', 'frio (<20ºC)', 'campo'): 'Relax solo en el campo de clima frio (<20ºC): te sugerimos Fiordland (Nueva Zelanda), Highlands (Escocia).',
    ('solo', 'relax', 'templado (20-28ºC)', 'playa'): 'Relax solo en una playa de clima templado (20-28ºC): te sugerimos Corfú (Grecia), Islas Cíes (España).',
    ('solo', 'relax', 'templado (20-28ºC)', 'ciudad'): 'Relax solo en una ciudad de clima templado (20-28ºC): te sugerimos Santiago de Chile, Lisboa, Buenos Aires.',
    ('solo', 'relax', 'templado (20-28ºC)', 'montaña'): 'Relax solo en una montaña de clima templado (20-28ºC): te sugerimos Montañas Apalaches (EE.UU.), Montañas Apalaches (EE.UU.), Montañas Apalaches (EE.UU.).',
    ('solo', 'relax', 'templado (20-28ºC)', 'campo'): 'Relax solo en el campo de clima templado (20-28ºC): te sugerimos Valle del Loira (Francia), Camino de Santiago (España), Napa Valley (EE.UU.).',
    ('solo', 'relax', 'calido (>28ºC)', 'playa'): 'Relax solo en una playa de clima calido (>28ºC): te sugerimos Zanzibar (Tanzania), Boracay (Filipinas), Praia do Forte (Brasil).',
    ('solo', 'relax', 'calido (>28ºC)', 'ciudad'): 'Relax solo en una ciudad de clima calido (>28ºC): te sugerimos Bangkok, La Habana.',
    ('solo', 'relax', 'calido (>28ºC)', 'montaña'): 'Relax solo en una montaña de clima calido (>28ºC): te sugerimos Sierra Nevada (Venezuela), Mocoa (Colombia).',
    ('solo', 'relax', 'calido (>28ºC)', 'campo'): 'Relax solo en el campo de clima calido (>28ºC): te sugerimos Yucatán (México).',
    ('solo', 'gastronomico', 'frio (<20ºC)', 'playa'): 'Gastronomico solo en una playa de clima frio (<20ºC): te sugerimos Sable Island (Canadá), Isla de Skye (Escocia).',
    ('solo', 'gastronomico', 'frio (<20ºC)', 'ciudad'): 'Gastronomico solo en una ciudad de clima frio (<20ºC): te sugerimos Reikiavik, Oslo.',
    ('solo', 'gastronomico', 'frio (<20ºC)', 'montaña'): 'Gastronomico solo en una montaña de clima frio (<20ºC): te sugerimos Zermatt (Suiza), Banff (Canadá).',
    ('solo', 'gastronomico', 'frio (<20ºC)', 'campo'): 'Gastronomico solo en el campo de clima frio (<20ºC): te sugerimos Fiordland (Nueva Zelanda), Highlands (Escocia).',
    ('solo', 'gastronomico', 'templado (20-28ºC)', 'playa'): 'Gastronomico solo en una playa de clima templado (20-28ºC): te sugerimos Corfú (Grecia), Islas Cíes (España), Bahía Magdalena (México).',
    ('solo', 'gastronomico', 'templado (20-28ºC)', 'ciudad'): 'Gastronomico solo en una ciudad de clima templado (20-28ºC): te sugerimos Buenos Aires, Lisboa.',
    ('solo', 'gastronomico', 'templado (20-28ºC)', 'montaña'): 'Gastronomico solo en una montaña de clima templado (20-28ºC): te sugerimos Sierra de Gredos (España), Montañas Apalaches (EE.UU.), Montañas Apalaches (EE.UU.).',
    ('solo', 'gastronomico', 'templado (20-28ºC)', 'campo'): 'Gastronomico solo en el campo de clima templado (20-28ºC): te sugerimos Valle del Loira (Francia), Camino de Santiago (España).',
    ('solo', 'gastronomico', 'calido (>28ºC)', 'playa'): 'Gastronomico solo en una playa de clima calido (>28ºC): te sugerimos Praia do Forte (Brasil), Boracay (Filipinas), Zanzibar (Tanzania).',
    ('solo', 'gastronomico', 'calido (>28ºC)', 'ciudad'): 'Gastronomico solo en una ciudad de clima calido (>28ºC): te sugerimos Cartagena (Colombia), Bangkok.',
    ('solo', 'gastronomico', 'calido (>28ºC)', 'montaña'): 'Gastronomico solo en una montaña de clima calido (>28ºC): te sugerimos Mocoa (Colombia), Cameron Highlands (Malasia), Sierra Nevada (Venezuela).',
    ('solo', 'gastronomico', 'calido (>28ºC)', 'campo'): 'Gastronomico solo en el campo de clima calido (>28ºC): te sugerimos Plaines de Luang Prabang (Laos), Yucatán (México), Delta del Mekong (Vietnam).',
    ('solo', 'cultural', 'frio (<20ºC)', 'playa'): 'Cultural solo en una playa de clima frio (<20ºC): te sugerimos Isla de Skye (Escocia), Sable Island (Canadá), Vik (Islandia).',
    ('solo', 'cultural', 'frio (<20ºC)', 'ciudad'): 'Cultural solo en una ciudad de clima frio (<20ºC): te sugerimos Oslo, Helsinki.',
    ('solo', 'cultural', 'frio (<20ºC)', 'montaña'): 'Cultural solo en una montaña de clima frio (<20ºC): te sugerimos Banff (Canadá), Zermatt (Suiza).',
    ('solo', 'cultural', 'frio (<20ºC)', 'campo'): 'Cultural solo en el campo de clima frio (<20ºC): te sugerimos Región de los Lagos (Alemania), Fiordland (Nueva Zelanda).',
    ('solo', 'cultural', 'templado (20-28ºC)', 'playa'): 'Cultural solo en una playa de clima templado (20-28ºC): te sugerimos Corfú (Grecia), Bahía Magdalena (México).',
    ('solo', 'cultural', 'templado (20-28ºC)', 'ciudad'): 'Cultural solo en una ciudad de clima templado (20-28ºC): te sugerimos Lisboa, Santiago de Chile.',
    ('solo', 'cultural', 'templado (20-28ºC)', 'montaña'): 'Cultural solo en una montaña de clima templado (20-28ºC): te sugerimos Tatras (Eslovaquia), Montañas Apalaches (EE.UU.).',
    ('solo', 'cultural', 'templado (20-28ºC)', 'campo'): 'Cultural solo en el campo de clima templado (20-28ºC): te sugerimos Napa Valley (EE.UU.), Napa Valley (EE.UU.), Napa Valley (EE.UU.).',
    ('solo', 'cultural', 'calido (>28ºC)', 'playa'): 'Cultural solo en una playa de clima calido (>28ºC): te sugerimos Boracay (Filipinas), Praia do Forte (Brasil), Zanzibar (Tanzania).',
    ('solo', 'cultural', 'calido (>28ºC)', 'ciudad'): 'Cultural solo en una ciudad de clima calido (>28ºC): te sugerimos La Habana.',
    ('solo', 'cultural', 'calido (>28ºC)', 'montaña'): 'Cultural solo en una montaña de clima calido (>28ºC): te sugerimos Sierra Nevada (Venezuela).',
    ('solo', 'cultural', 'calido (>28ºC)', 'campo'): 'Cultural solo en el campo de clima calido (>28ºC): te sugerimos Delta del Mekong (Vietnam), Yucatán (México), Plaines de Luang Prabang (Laos).',
    ('pareja', 'aventura', 'frio (<20ºC)', 'playa'): 'Una Aventura con pareja en una playa de clima frio (<20ºC): te sugerimos Isla de Skye (Escocia).',
    ('pareja', 'aventura', 'frio (<20ºC)', 'ciudad'): 'Una Aventura con pareja en una ciudad de clima frio (<20ºC): te sugerimos Reikiavik, Helsinki, Oslo.',
    ('pareja', 'aventura', 'frio (<20ºC)', 'montaña'): 'Una Aventura con pareja en una montaña de clima frio (<20ºC): te sugerimos Zermatt (Suiza), Banff (Canadá).',
    ('pareja', 'aventura', 'frio (<20ºC)', 'campo'): 'Una Aventura con pareja en el campo de clima frio (<20ºC): te sugerimos Fiordland (Nueva Zelanda), Highlands (Escocia).',
    ('pareja', 'aventura', 'templado (20-28ºC)', 'playa'): 'Una Aventura con pareja en una playa de clima templado (20-28ºC): te sugerimos Islas Cíes (España), Corfú (Grecia).',
    ('pareja', 'aventura', 'templado (20-28ºC)', 'ciudad'): 'Una Aventura con pareja en una ciudad de clima templado (20-28ºC): te sugerimos Buenos Aires, Lisboa.',
    ('pareja', 'aventura', 'templado (20-28ºC)', 'montaña'): 'Una Aventura con pareja en una montaña de clima templado (20-28ºC): te sugerimos Tatras (Eslovaquia), Sierra de Gredos (España).',
    ('pareja', 'aventura', 'templado (20-28ºC)', 'campo'): 'Una Aventura con pareja en el campo de clima templado (20-28ºC): te sugerimos Napa Valley (EE.UU.), Napa Valley (EE.UU.), Camino de Santiago (España).',
    ('pareja', 'aventura', 'calido (>28ºC)', 'playa'): 'Una Aventura con pareja en una playa de clima calido (>28ºC): te sugerimos Zanzibar (Tanzania), Praia do Forte (Brasil).',
    ('pareja', 'aventura', 'calido (>28ºC)', 'ciudad'): 'Una Aventura con pareja en una ciudad de clima calido (>28ºC): te sugerimos Cartagena (Colombia), Bangkok.',
    ('pareja', 'aventura', 'calido (>28ºC)', 'montaña'): 'Una Aventura con pareja en una montaña de clima calido (>28ºC): te sugerimos Cameron Highlands (Malasia), Sierra Nevada (Venezuela).',
    ('pareja', 'aventura', 'calido (>28ºC)', 'campo'): 'Una Aventura con pareja en el campo de clima calido (>28ºC): te sugerimos Plaines de Luang Prabang (Laos), Yucatán (México).',
    ('pareja', 'relax', 'frio (<20ºC)', 'playa'): 'Relax con pareja en una playa de clima frio (<20ºC): te sugerimos Isla de Skye (Escocia).',
    ('pareja', 'relax', 'frio (<20ºC)', 'ciudad'): 'Relax con pareja en una ciudad de clima frio (<20ºC): te sugerimos Helsinki, Reikiavik, Oslo.',
    ('pareja', 'relax', 'frio (<20ºC)', 'montaña'): 'Relax con pareja en una montaña de clima frio (<20ºC): te sugerimos Zermatt (Suiza), Banff (Canadá).',
    ('pareja', 'relax', 'frio (<20ºC)', 'campo'): 'Relax con pareja en el campo de clima frio (<20ºC): te sugerimos Fiordland (Nueva Zelanda), Región de los Lagos (Alemania), Highlands (Escocia).',
    ('pareja', 'relax', 'templado (20-28ºC)', 'playa'): 'Relax con pareja en una playa de clima templado (20-28ºC): te sugerimos Corfú (Grecia), Islas Cíes (España).',
    ('pareja', 'relax', 'templado (20-28ºC)', 'ciudad'): 'Relax con pareja en una ciudad de clima templado (20-28ºC): te sugerimos Lisboa, Santiago de Chile, Buenos Aires.',
    ('pareja', 'relax', 'templado (20-28ºC)', 'montaña'): 'Relax con pareja en una montaña de clima templado (20-28ºC): te sugerimos Tatras (Eslovaquia), Montañas Apalaches (EE.UU.), Sierra de Gredos (España).',
    ('pareja', 'relax', 'templado (20-28ºC)', 'campo'): 'Relax con pareja en el campo de clima templado (20-28ºC): te sugerimos Valle del Loira (Francia), Camino de Santiago (España).',
    ('pareja', 'relax', 'calido (>28ºC)', 'playa'): 'Relax con pareja en una playa de clima calido (>28ºC): te sugerimos Boracay (Filipinas), Praia do Forte (Brasil).',
    ('pareja', 'relax', 'calido (>28ºC)', 'ciudad'): 'Relax con pareja en una ciudad de clima calido (>28ºC): te sugerimos La Habana, Bangkok.',
    ('pareja', 'relax', 'calido (>28ºC)', 'montaña'): 'Relax con pareja en una montaña de clima calido (>28ºC): te sugerimos Mocoa (Colombia), Sierra Nevada (Venezuela).',
    ('pareja', 'relax', 'calido (>28ºC)', 'campo'): 'Relax con pareja en el campo de clima calido (>28ºC): te sugerimos Delta del Mekong (Vietnam), Plaines de Luang Prabang (Laos).',
    ('pareja', 'gastronomico', 'frio (<20ºC)', 'playa'): 'Gastronomico con pareja en una playa de clima frio (<20ºC): te sugerimos Vik (Islandia), Isla de Skye (Escocia).',
    ('pareja', 'gastronomico', 'frio (<20ºC)', 'ciudad'): 'Gastronomico con pareja en una ciudad de clima frio (<20ºC): te sugerimos Reikiavik.',
    ('pareja', 'gastronomico', 'frio (<20ºC)', 'montaña'): 'Gastronomico con pareja en una montaña de clima frio (<20ºC): te sugerimos Banff (Canadá), Zermatt (Suiza).',
    ('pareja', 'gastronomico', 'frio (<20ºC)', 'campo'): 'Gastronomico con pareja en el campo de clima frio (<20ºC): te sugerimos Región de los Lagos (Alemania), Fiordland (Nueva Zelanda), Highlands (Escocia).',
    ('pareja', 'gastronomico', 'templado (20-28ºC)', 'playa'): 'Gastronomico con pareja en una playa de clima templado (20-28ºC): te sugerimos Islas Cíes (España), Bahía Magdalena (México).',
    ('pareja', 'gastronomico', 'templado (20-28ºC)', 'ciudad'): 'Gastronomico con pareja en una ciudad de clima templado (20-28ºC): te sugerimos Lisboa, Buenos Aires.',
    ('pareja', 'gastronomico', 'templado (20-28ºC)', 'montaña'): 'Gastronomico con pareja en una montaña de clima templado (20-28ºC): te sugerimos Sierra de Gredos (España), Montañas Apalaches (EE.UU.), Sierra de Gredos (España).',
    ('pareja', 'gastronomico', 'templado (20-28ºC)', 'campo'): 'Gastronomico con pareja en el campo de clima templado (20-28ºC): te sugerimos Valle del Loira (Francia), Napa Valley (EE.UU.), Napa Valley (EE.UU.).',
    ('pareja', 'gastronomico', 'calido (>28ºC)', 'playa'): 'Gastronomico con pareja en una playa de clima calido (>28ºC): te sugerimos Praia do Forte (Brasil), Boracay (Filipinas), Zanzibar (Tanzania).',
    ('pareja', 'gastronomico', 'calido (>28ºC)', 'ciudad'): 'Gastronomico con pareja en una ciudad de clima calido (>28ºC): te sugerimos La Habana, Cartagena (Colombia).',
    ('pareja', 'gastronomico', 'calido (>28ºC)', 'montaña'): 'Gastronomico con pareja en una montaña de clima calido (>28ºC): te sugerimos Mocoa (Colombia), Cameron Highlands (Malasia), Sierra Nevada (Venezuela).',
    ('pareja', 'gastronomico', 'calido (>28ºC)', 'campo'): 'Gastronomico con pareja en el campo de clima calido (>28ºC): te sugerimos Yucatán (México), Plaines de Luang Prabang (Laos), Delta del Mekong (Vietnam).',
    ('pareja', 'cultural', 'frio (<20ºC)', 'playa'): 'Cultural con pareja en una playa de clima frio (<20ºC): te sugerimos Vik (Islandia), Isla de Skye (Escocia).',
    ('pareja', 'cultural', 'frio (<20ºC)', 'ciudad'): 'Cultural con pareja en una ciudad de clima frio (<20ºC): te sugerimos Reikiavik, Oslo.',
    ('pareja', 'cultural', 'frio (<20ºC)', 'montaña'): 'Cultural con pareja en una montaña de clima frio (<20ºC): te sugerimos Banff (Canadá), Zermatt (Suiza), Tirol (Austria).',
    ('pareja', 'cultural', 'frio (<20ºC)', 'campo'): 'Cultural con pareja en el campo de clima frio (<20ºC): te sugerimos Región de los Lagos (Alemania), Fiordland (Nueva Zelanda).',
    ('pareja', 'cultural', 'templado (20-28ºC)', 'playa'): 'Cultural con pareja en una playa de clima templado (20-28ºC): te sugerimos Islas Cíes (España), Corfú (Grecia).',
    ('pareja', 'cultural', 'templado (20-28ºC)', 'ciudad'): 'Cultural con pareja en una ciudad de clima templado (20-28ºC): te sugerimos Buenos Aires, Santiago de Chile, Lisboa.',
    ('pareja', 'cultural', 'templado (20-28ºC)', 'montaña'): 'Cultural con pareja en una montaña de clima templado (20-28ºC): te sugerimos Tatras (Eslovaquia), Montañas Apalaches (EE.UU.), Sierra de Gredos (España).',
    ('pareja', 'cultural', 'templado (20-28ºC)', 'campo'): 'Cultural con pareja en el campo de clima templado (20-28ºC): te sugerimos Camino de Santiago (España), Napa Valley (EE.UU.), Valle del Loira (Francia).',
    ('pareja', 'cultural', 'calido (>28ºC)', 'playa'): 'Cultural con pareja en una playa de clima calido (>28ºC): te sugerimos Praia do Forte (Brasil).',
    ('pareja', 'cultural', 'calido (>28ºC)', 'ciudad'): 'Cultural con pareja en una ciudad de clima calido (>28ºC): te sugerimos Cartagena (Colombia).',
    ('pareja', 'cultural', 'calido (>28ºC)', 'montaña'): 'Cultural con pareja en una montaña de clima calido (>28ºC): te sugerimos Sierra Nevada (Venezuela), Mocoa (Colombia).',
    ('pareja', 'cultural', 'calido (>28ºC)', 'campo'): 'Cultural con pareja en el campo de clima calido (>28ºC): te sugerimos Yucatán (México), Plaines de Luang Prabang (Laos).',
    ('amigos', 'aventura', 'frio (<20ºC)', 'playa'): 'Una Aventura con amigos en una playa de clima frio (<20ºC): te sugerimos Vik (Islandia), Sable Island (Canadá).',
    ('amigos', 'aventura', 'frio (<20ºC)', 'ciudad'): 'Una Aventura con amigos en una ciudad de clima frio (<20ºC): te sugerimos Reikiavik.',
    ('amigos', 'aventura', 'frio (<20ºC)', 'montaña'): 'Una Aventura con amigos en una montaña de clima frio (<20ºC): te sugerimos Banff (Canadá), Zermatt (Suiza).',
    ('amigos', 'aventura', 'frio (<20ºC)', 'campo'): 'Una Aventura con amigos en el campo de clima frio (<20ºC): te sugerimos Región de los Lagos (Alemania), Highlands (Escocia).',
    ('amigos', 'aventura', 'templado (20-28ºC)', 'playa'): 'Una Aventura con amigos en una playa de clima templado (20-28ºC): te sugerimos Bahía Magdalena (México), Islas Cíes (España).',
    ('amigos', 'aventura', 'templado (20-28ºC)', 'ciudad'): 'Una Aventura con amigos en una ciudad de clima templado (20-28ºC): te sugerimos Buenos Aires, Lisboa.',
    ('amigos', 'aventura', 'templado (20-28ºC)', 'montaña'): 'Una Aventura con amigos en una montaña de clima templado (20-28ºC): te sugerimos Sierra de Gredos (España), Montañas Apalaches (EE.UU.), Tatras (Eslovaquia).',
    ('amigos', 'aventura', 'templado (20-28ºC)', 'campo'): 'Una Aventura con amigos en el campo de clima templado (20-28ºC): te sugerimos Camino de Santiago (España).',
    ('amigos', 'aventura', 'calido (>28ºC)', 'playa'): 'Una Aventura con amigos en una playa de clima calido (>28ºC): te sugerimos Zanzibar (Tanzania), Boracay (Filipinas).',
    ('amigos', 'aventura', 'calido (>28ºC)', 'ciudad'): 'Una Aventura con amigos en una ciudad de clima calido (>28ºC): te sugerimos Bangkok, Cartagena (Colombia).',
    ('amigos', 'aventura', 'calido (>28ºC)', 'montaña'): 'Una Aventura con amigos en una montaña de clima calido (>28ºC): te sugerimos Cameron Highlands (Malasia), Mocoa (Colombia), Sierra Nevada (Venezuela).',
    ('amigos', 'aventura', 'calido (>28ºC)', 'campo'): 'Una Aventura con amigos en el campo de clima calido (>28ºC): te sugerimos Plaines de Luang Prabang (Laos), Yucatán (México).',
    ('amigos', 'relax', 'frio (<20ºC)', 'playa'): 'Relax con amigos en una playa de clima frio (<20ºC): te sugerimos Isla de Skye (Escocia).',
    ('amigos', 'relax', 'frio (<20ºC)', 'ciudad'): 'Relax con amigos en una ciudad de clima frio (<20ºC): te sugerimos Helsinki, Oslo, Reikiavik.',
    ('amigos', 'relax', 'frio (<20ºC)', 'montaña'): 'Relax con amigos en una montaña de clima frio (<20ºC): te sugerimos Banff (Canadá), Tirol (Austria).',
    ('amigos', 'relax', 'frio (<20ºC)', 'campo'): 'Relax con amigos en el campo de clima frio (<20ºC): te sugerimos Fiordland (Nueva Zelanda), Highlands (Escocia).',
    ('amigos', 'relax', 'templado (20-28ºC)', 'playa'): 'Relax con amigos en una playa de clima templado (20-28ºC): te sugerimos Corfú (Grecia), Islas Cíes (España).',
    ('amigos', 'relax', 'templado (20-28ºC)', 'ciudad'): 'Relax con amigos en una ciudad de clima templado (20-28ºC): te sugerimos Santiago de Chile, Lisboa.',
    ('amigos', 'relax', 'templado (20-28ºC)', 'montaña'): 'Relax con amigos en una montaña de clima templado (20-28ºC): te sugerimos Tatras (Eslovaquia), Sierra de Gredos (España).',
    ('amigos', 'relax', 'templado (20-28ºC)', 'campo'): 'Relax con amigos en el campo de clima templado (20-28ºC): te sugerimos Napa Valley (EE.UU.), Napa Valley (EE.UU.), Camino de Santiago (España).',
    ('amigos', 'relax', 'calido (>28ºC)', 'playa'): 'Relax con amigos en una playa de clima calido (>28ºC): te sugerimos Zanzibar (Tanzania).',
    ('amigos', 'relax', 'calido (>28ºC)', 'ciudad'): 'Relax con amigos en una ciudad de clima calido (>28ºC): te sugerimos Bangkok, La Habana.',
    ('amigos', 'relax', 'calido (>28ºC)', 'montaña'): 'Relax con amigos en una montaña de clima calido (>28ºC): te sugerimos Mocoa (Colombia), Cameron Highlands (Malasia).',
    ('amigos', 'relax', 'calido (>28ºC)', 'campo'): 'Relax con amigos en el campo de clima calido (>28ºC): te sugerimos Yucatán (México), Delta del Mekong (Vietnam), Plaines de Luang Prabang (Laos).',
    ('amigos', 'gastronomico', 'frio (<20ºC)', 'playa'): 'Gastronomico con amigos en una playa de clima frio (<20ºC): te sugerimos Isla de Skye (Escocia), Vik (Islandia).',
    ('amigos', 'gastronomico', 'frio (<20ºC)', 'ciudad'): 'Gastronomico con amigos en una ciudad de clima frio (<20ºC): te sugerimos Oslo, Reikiavik.',
    ('amigos', 'gastronomico', 'frio (<20ºC)', 'montaña'): 'Gastronomico con amigos en una montaña de clima frio (<20ºC): te sugerimos Zermatt (Suiza), Tirol (Austria).',
    ('amigos', 'gastronomico', 'frio (<20ºC)', 'campo'): 'Gastronomico con amigos en el campo de clima frio (<20ºC): te sugerimos Fiordland (Nueva Zelanda), Highlands (Escocia).',
    ('amigos', 'gastronomico', 'templado (20-28ºC)', 'playa'): 'Gastronomico con amigos en una playa de clima templado (20-28ºC): te sugerimos Islas Cíes (España), Bahía Magdalena (México), Corfú (Grecia).',
    ('amigos', 'gastronomico', 'templado (20-28ºC)', 'ciudad'): 'Gastronomico con amigos en una ciudad de clima templado (20-28ºC): te sugerimos Lisboa.',
    ('amigos', 'gastronomico', 'templado (20-28ºC)', 'montaña'): 'Gastronomico con amigos en una montaña de clima templado (20-28ºC): te sugerimos Montañas Apalaches (EE.UU.), Tatras (Eslovaquia), Montañas Apalaches (EE.UU.).',
    ('amigos', 'gastronomico', 'templado (20-28ºC)', 'campo'): 'Gastronomico con amigos en el campo de clima templado (20-28ºC): te sugerimos Napa Valley (EE.UU.), Valle del Loira (Francia), Valle del Loira (Francia).',
    ('amigos', 'gastronomico', 'calido (>28ºC)', 'playa'): 'Gastronomico con amigos en una playa de clima calido (>28ºC): te sugerimos Boracay (Filipinas), Zanzibar (Tanzania).',
    ('amigos', 'gastronomico', 'calido (>28ºC)', 'ciudad'): 'Gastronomico con amigos en una ciudad de clima calido (>28ºC): te sugerimos Bangkok, La Habana.',
    ('amigos', 'gastronomico', 'calido (>28ºC)', 'montaña'): 'Gastronomico con amigos en una montaña de clima calido (>28ºC): te sugerimos Mocoa (Colombia), Sierra Nevada (Venezuela).',
    ('amigos', 'gastronomico', 'calido (>28ºC)', 'campo'): 'Gastronomico con amigos en el campo de clima calido (>28ºC): te sugerimos Plaines de Luang Prabang (Laos), Yucatán (México).',
    ('amigos', 'cultural', 'frio (<20ºC)', 'playa'): 'Cultural con amigos en una playa de clima frio (<20ºC): te sugerimos Isla de Skye (Escocia), Vik (Islandia).',
    ('amigos', 'cultural', 'frio (<20ºC)', 'ciudad'): 'Cultural con amigos en una ciudad de clima frio (<20ºC): te sugerimos Helsinki, Reikiavik.',
    ('amigos', 'cultural', 'frio (<20ºC)', 'montaña'): 'Cultural con amigos en una montaña de clima frio (<20ºC): te sugerimos Zermatt (Suiza), Banff (Canadá).',
    ('amigos', 'cultural', 'frio (<20ºC)', 'campo'): 'Cultural con amigos en el campo de clima frio (<20ºC): te sugerimos Región de los Lagos (Alemania), Fiordland (Nueva Zelanda).',
    ('amigos', 'cultural', 'templado (20-28ºC)', 'playa'): 'Cultural con amigos en una playa de clima templado (20-28ºC): te sugerimos Corfú (Grecia), Islas Cíes (España), Bahía Magdalena (México).',
    ('amigos', 'cultural', 'templado (20-28ºC)', 'ciudad'): 'Cultural con amigos en una ciudad de clima templado (20-28ºC): te sugerimos Buenos Aires, Santiago de Chile, Lisboa.',
    ('amigos', 'cultural', 'templado (20-28ºC)', 'montaña'): 'Cultural con amigos en una montaña de clima templado (20-28ºC): te sugerimos Tatras (Eslovaquia), Sierra de Gredos (España).',
    ('amigos', 'cultural', 'templado (20-28ºC)', 'campo'): 'Cultural con amigos en el campo de clima templado (20-28ºC): te sugerimos Camino de Santiago (España), Napa Valley (EE.UU.), Camino de Santiago (España).',
    ('amigos', 'cultural', 'calido (>28ºC)', 'playa'): 'Cultural con amigos en una playa de clima calido (>28ºC): te sugerimos Praia do Forte (Brasil), Zanzibar (Tanzania), Boracay (Filipinas).',
    ('amigos', 'cultural', 'calido (>28ºC)', 'ciudad'): 'Cultural con amigos en una ciudad de clima calido (>28ºC): te sugerimos La Habana, Cartagena (Colombia).',
    ('amigos', 'cultural', 'calido (>28ºC)', 'montaña'): 'Cultural con amigos en una montaña de clima calido (>28ºC): te sugerimos Mocoa (Colombia), Sierra Nevada (Venezuela).',
    ('amigos', 'cultural', 'calido (>28ºC)', 'campo'): 'Cultural con amigos en el campo de clima calido (>28ºC): te sugerimos Plaines de Luang Prabang (Laos), Delta del Mekong (Vietnam), Yucatán (México).',
    ('familia', 'aventura', 'frio (<20ºC)', 'playa'): 'Una Aventura con familia en una playa de clima frio (<20ºC): te sugerimos Vik (Islandia), Sable Island (Canadá).',
    ('familia', 'aventura', 'frio (<20ºC)', 'ciudad'): 'Una Aventura con familia en una ciudad de clima frio (<20ºC): te sugerimos Reikiavik, Helsinki, Oslo.',
    ('familia', 'aventura', 'frio (<20ºC)', 'montaña'): 'Una Aventura con familia en una montaña de clima frio (<20ºC): te sugerimos Banff (Canadá), Zermatt (Suiza).',
    ('familia', 'aventura', 'frio (<20ºC)', 'campo'): 'Una Aventura con familia en el campo de clima frio (<20ºC): te sugerimos Región de los Lagos (Alemania), Highlands (Escocia).',
    ('familia', 'aventura', 'templado (20-28ºC)', 'playa'): 'Una Aventura con familia en una playa de clima templado (20-28ºC): te sugerimos Islas Cíes (España), Corfú (Grecia).',
    ('familia', 'aventura', 'templado (20-28ºC)', 'ciudad'): 'Una Aventura con familia en una ciudad de clima templado (20-28ºC): te sugerimos Lisboa, Santiago de Chile.',
    ('familia', 'aventura', 'templado (20-28ºC)', 'montaña'): 'Una Aventura con familia en una montaña de clima templado (20-28ºC): te sugerimos Sierra de Gredos (España), Montañas Apalaches (EE.UU.), Montañas Apalaches (EE.UU.).',
    ('familia', 'aventura', 'templado (20-28ºC)', 'campo'): 'Una Aventura con familia en el campo de clima templado (20-28ºC): te sugerimos Camino de Santiago (España), Valle del Loira (Francia), Napa Valley (EE.UU.).',
    ('familia', 'aventura', 'calido (>28ºC)', 'playa'): 'Una Aventura con familia en una playa de clima calido (>28ºC): te sugerimos Praia do Forte (Brasil), Zanzibar (Tanzania).',
    ('familia', 'aventura', 'calido (>28ºC)', 'ciudad'): 'Una Aventura con familia en una ciudad de clima calido (>28ºC): te sugerimos La Habana, Cartagena (Colombia), Bangkok.',
    ('familia', 'aventura', 'calido (>28ºC)', 'montaña'): 'Una Aventura con familia en una montaña de clima calido (>28ºC): te sugerimos Cameron Highlands (Malasia), Mocoa (Colombia), Sierra Nevada (Venezuela).',
    ('familia', 'aventura', 'calido (>28ºC)', 'campo'): 'Una Aventura con familia en el campo de clima calido (>28ºC): te sugerimos Plaines de Luang Prabang (Laos), Yucatán (México).',
    ('familia', 'relax', 'frio (<20ºC)', 'playa'): 'Relax con familia en una playa de clima frio (<20ºC): te sugerimos Sable Island (Canadá), Isla de Skye (Escocia).',
    ('familia', 'relax', 'frio (<20ºC)', 'ciudad'): 'Relax con familia en una ciudad de clima frio (<20ºC): te sugerimos Reikiavik, Helsinki, Oslo.',
    ('familia', 'relax', 'frio (<20ºC)', 'montaña'): 'Relax con familia en una montaña de clima frio (<20ºC): te sugerimos Tirol (Austria), Zermatt (Suiza).',
    ('familia', 'relax', 'frio (<20ºC)', 'campo'): 'Relax con familia en el campo de clima frio (<20ºC): te sugerimos Highlands (Escocia), Región de los Lagos (Alemania).',
    ('familia', 'relax', 'templado (20-28ºC)', 'playa'): 'Relax con familia en una playa de clima templado (20-28ºC): te sugerimos Corfú (Grecia).',
    ('familia', 'relax', 'templado (20-28ºC)', 'ciudad'): 'Relax con familia en una ciudad de clima templado (20-28ºC): te sugerimos Lisboa, Santiago de Chile.',
    ('familia', 'relax', 'templado (20-28ºC)', 'montaña'): 'Relax con familia en una montaña de clima templado (20-28ºC): te sugerimos Montañas Apalaches (EE.UU.), Sierra de Gredos (España), Montañas Apalaches (EE.UU.).',
    ('familia', 'relax', 'templado (20-28ºC)', 'campo'): 'Relax con familia en el campo de clima templado (20-28ºC): te sugerimos Camino de Santiago (España), Valle del Loira (Francia).',
    ('familia', 'relax', 'calido (>28ºC)', 'playa'): 'Relax con familia en una playa de clima calido (>28ºC): te sugerimos Praia do Forte (Brasil), Zanzibar (Tanzania), Boracay (Filipinas).',
    ('familia', 'relax', 'calido (>28ºC)', 'ciudad'): 'Relax con familia en una ciudad de clima calido (>28ºC): te sugerimos La Habana, Bangkok, Cartagena (Colombia).',
    ('familia', 'relax', 'calido (>28ºC)', 'montaña'): 'Relax con familia en una montaña de clima calido (>28ºC): te sugerimos Sierra Nevada (Venezuela), Cameron Highlands (Malasia).',
    ('familia', 'relax', 'calido (>28ºC)', 'campo'): 'Relax con familia en el campo de clima calido (>28ºC): te sugerimos Delta del Mekong (Vietnam), Yucatán (México).',
    ('familia', 'gastronomico', 'frio (<20ºC)', 'playa'): 'Gastronomico con familia en una playa de clima frio (<20ºC): te sugerimos Vik (Islandia), Isla de Skye (Escocia).',
    ('familia', 'gastronomico', 'frio (<20ºC)', 'ciudad'): 'Gastronomico con familia en una ciudad de clima frio (<20ºC): te sugerimos Reikiavik.',
    ('familia', 'gastronomico', 'frio (<20ºC)', 'montaña'): 'Gastronomico con familia en una montaña de clima frio (<20ºC): te sugerimos Tirol (Austria), Banff (Canadá).',
    ('familia', 'gastronomico', 'frio (<20ºC)', 'campo'): 'Gastronomico con familia en el campo de clima frio (<20ºC): te sugerimos Región de los Lagos (Alemania), Highlands (Escocia), Fiordland (Nueva Zelanda).',
    ('familia', 'gastronomico', 'templado (20-28ºC)', 'playa'): 'Gastronomico con familia en una playa de clima templado (20-28ºC): te sugerimos Islas Cíes (España), Bahía Magdalena (México).',
    ('familia', 'gastronomico', 'templado (20-28ºC)', 'ciudad'): 'Gastronomico con familia en una ciudad de clima templado (20-28ºC): te sugerimos Buenos Aires, Santiago de Chile.',
    ('familia', 'gastronomico', 'templado (20-28ºC)', 'montaña'): 'Gastronomico con familia en una montaña de clima templado (20-28ºC): te sugerimos Tatras (Eslovaquia), Sierra de Gredos (España).',
    ('familia', 'gastronomico', 'templado (20-28ºC)', 'campo'): 'Gastronomico con familia en el campo de clima templado (20-28ºC): te sugerimos Camino de Santiago (España), Napa Valley (EE.UU.).',
    ('familia', 'gastronomico', 'calido (>28ºC)', 'playa'): 'Gastronomico con familia en una playa de clima calido (>28ºC): te sugerimos Boracay (Filipinas), Praia do Forte (Brasil), Zanzibar (Tanzania).',
    ('familia', 'gastronomico', 'calido (>28ºC)', 'ciudad'): 'Gastronomico con familia en una ciudad de clima calido (>28ºC): te sugerimos Cartagena (Colombia), Bangkok.',
    ('familia', 'gastronomico', 'calido (>28ºC)', 'montaña'): 'Gastronomico con familia en una montaña de clima calido (>28ºC): te sugerimos Mocoa (Colombia), Sierra Nevada (Venezuela).',
    ('familia', 'gastronomico', 'calido (>28ºC)', 'campo'): 'Gastronomico con familia en el campo de clima calido (>28ºC): te sugerimos Plaines de Luang Prabang (Laos), Delta del Mekong (Vietnam).',
    ('familia', 'cultural', 'frio (<20ºC)', 'playa'): 'Cultural con familia en una playa de clima frio (<20ºC): te sugerimos Vik (Islandia).',
    ('familia', 'cultural', 'frio (<20ºC)', 'ciudad'): 'Cultural con familia en una ciudad de clima frio (<20ºC): te sugerimos Reikiavik, Helsinki.',
    ('familia', 'cultural', 'frio (<20ºC)', 'montaña'): 'Cultural con familia en una montaña de clima frio (<20ºC): te sugerimos Tirol (Austria), Zermatt (Suiza).',
    ('familia', 'cultural', 'frio (<20ºC)', 'campo'): 'Cultural con familia en el campo de clima frio (<20ºC): te sugerimos Fiordland (Nueva Zelanda), Región de los Lagos (Alemania).',
    ('familia', 'cultural', 'templado (20-28ºC)', 'playa'): 'Cultural con familia en una playa de clima templado (20-28ºC): te sugerimos Islas Cíes (España), Corfú (Grecia).',
    ('familia', 'cultural', 'templado (20-28ºC)', 'ciudad'): 'Cultural con familia en una ciudad de clima templado (20-28ºC): te sugerimos Buenos Aires, Santiago de Chile, Lisboa.',
    ('familia', 'cultural', 'templado (20-28ºC)', 'montaña'): 'Cultural con familia en una montaña de clima templado (20-28ºC): te sugerimos Montañas Apalaches (EE.UU.), Montañas Apalaches (EE.UU.), Tatras (Eslovaquia).',
    ('familia', 'cultural', 'templado (20-28ºC)', 'campo'): 'Cultural con familia en el campo de clima templado (20-28ºC): te sugerimos Valle del Loira (Francia), Napa Valley (EE.UU.), Camino de Santiago (España).',
    ('familia', 'cultural', 'calido (>28ºC)', 'playa'): 'Cultural con familia en una playa de clima calido (>28ºC): te sugerimos Boracay (Filipinas), Praia do Forte (Brasil).',
    ('familia', 'cultural', 'calido (>28ºC)', 'ciudad'): 'Cultural con familia en una ciudad de clima calido (>28ºC): te sugerimos Bangkok, La Habana.',
    ('familia', 'cultural', 'calido (>28ºC)', 'montaña'): 'Cultural con familia en una montaña de clima calido (>28ºC): te sugerimos Cameron Highlands (Malasia), Mocoa (Colombia).',
    ('familia', 'cultural', 'calido (>28ºC)', 'campo'): 'Cultural con familia en el campo de clima calido (>28ºC): te sugerimos Delta del Mekong (Vietnam), Yucatán (México).',
}

def obtener_recomendacion(compania, tipo_viaje, clima, preferencia):
    clave = (compania, tipo_viaje, clima, preferencia)
    return recomendaciones.get(clave, "Lo sentimos, aún no tenemos una recomendación específica para esta combinación. Pronto estará disponible.")

def interfaz_viaje():
    print("=== Asistente de Recomendación de Viaje ===")

    def elegir(mensaje, opciones):
        print("\n" + mensaje + "\n")
        for i, o in enumerate(opciones, 1):
            print(f"{i}. {o}")
        while True:
            try:
                eleccion = int(input("\nElige una opción: "))
                if 1 <= eleccion <= len(opciones):
                    return opciones[eleccion - 1]
            except ValueError:
                pass
            print("Opción inválida. Intenta de nuevo.")

    comp = elegir("¿Con quién viajas?", companias)
    viaje = elegir("¿Cuál es el tipo de viaje?", tipos_viaje)
    clima = elegir("¿Qué clima prefieres?", climas)
    pref = elegir("¿Qué tipo de lugar prefieres?", preferencias)

    print("\n Recomendación:")
    print(obtener_recomendacion(comp, viaje, clima, pref))

if __name__ == "__main__":
    interfaz_viaje()
